### ISSUE TITLE
enemies sometimes aim nowhere

### ISSUE THREAD

**Issue by dariormt** [Nullptr-Studios/Project-Hotline#291]

**Comment by dariormt** [comment]
I didn´t see this in the pre-release build :0

**Comment by ynks** [comment]
you can see it in the bossfight :)

**Comment by dariormt** [comment]
that's the thing, the bossfight was impossible cuz the enemy aimed correctly

**Comment by ynks** [comment]
oh... git gud di castillo

**Comment by dariormt** [comment]
Im so pissed, this still happens, it´s going to the release
