### ISSUE TITLE
Weapon System

### ISSUE THREAD

**Issue by dariormt** [Nullptr-Studios/Project-Hotline#49]
- [x] #56
- [x] #3 
- [x] #4 
- [x] #57
- [x] #58

**Comment by dariormt** [comment]
There are still bugs, :)

**Comment by ynks** [comment]
@dariormt can you change the grab weapon button to `square` and `E` and make it so `playerInput.cs` calls the `input.Enable` and `input.Disable` (for disabling input when on dialogue)
