### ISSUE TITLE
Fix bullet dispersion curve

### ISSUE THREAD

**Issue by ynks** [Nullptr-Studios/Project-Hotline#71]
BDC cannot be edited

https://github.com/user-attachments/assets/d281d8aa-0a84-43ed-a7ef-c22387d05b48

Proposed solution: get rid of the min and max dispersion angle and read them directly from the curve itself as we can put values greater than one. We can just set the curve between 5 and 25 if we want those values for example

**Comment by dariormt** [comment]
Ok, I will add an option to override the curve
